# Version of docker-compose
version: '3'

services:

  #############################################################
  ####################     APPLICATIONS    ####################
  #############################################################


  # getting webservice image
 # webservice:
 #   image: autodoc_service
 #   container_name: autodoc-webservice
 #   build: Apps/autodoc-webservice/.
 #   ports:
 #    - 8087:8080
    #volumes:
     # - logs:/usr/app/resources
 #   depends_on:
 #     - autodoc-db-dev
 #   networks:
 #     - autodoc

   # getting webservice image
 # webapp:
 #   image: autodoc_app
 #   container_name: autodoc-webapp
 #   build: Apps/autodoc-webapp/.
 #   ports:
 #    - 8084:8080
 #   depends_on:
 #     - webservice
 #   networks:
 #     - autodoc    
 
  #############################################################
  ####################     DATABASES       ####################
  #############################################################

  autodoc-db-dev:
    image: postgres:11
    container_name: autodoc-db-dev
    ports:
      - 5132:5432
    environment:
      POSTGRES_USER: ocp
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: autodoc
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ".Databases/db-initProd/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - autodoc

  autodoc-db-QA:
    image: postgres:11
    container_name: autodoc-db-QA
    ports:
      - 5232:5432
    environment:
      POSTGRES_USER: ocp
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: autodoc
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ".Databases/db-initProd/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - autodoc       


  autodoc-db-preprod:
    image: postgres:11
    container_name: autodoc-db-preprod
    ports:
      - 5332:5432
    environment:
      POSTGRES_USER: ocp
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: autodoc
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ".Databases/db-initProd/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - autodoc

  autodoc-db-production:
    image: postgres:11
    container_name: autodoc-db-production
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ocp
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: autodoc
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ".Databases/db-initProd/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - autodoc

  #############################################################
  ####################     SONARQUBE       ####################
  #############################################################

  sonarqube:
    container_name: sonarqube
    build:
      context: sonarqube/
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - ./sonarqube/sonarqube_home:/opt/sonarqube/data 
    networks:
      - autodoc  
    command: -Dsonar.ce.javaOpts=-Xmx2040m

  #############################################################
  ####################     JENKINS      #######################
  #############################################################

  jenkins:
    container_name: jenkins
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 4001:5000
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube
    networks:
      - autodoc    
 
###########   volumes   ###################

networks:
  autodoc: