# Version of docker-compose
version: '3'

services:
  #############################################################
  ####################     SONARQUBE       ####################
  #############################################################

  sonarqube:
    build:
      context: sonarqube/
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
    networks:
      - autodoc  
    environment:
      - sonar.jdbc.url=jdbc:postgresql://dbsonar:5432/sonar
    volumes:
      - ./sonarqube/sonarqube_home:/opt/sonarqube/data
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_extensions:/opt/sonarqube/extensions  
  dbsonar:
    image: postgres:11
    networks:
      - autodoc
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

  #############################################################
  ####################     JENKINS       ######################
  #############################################################

  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 4000:5000
    container_name: jenkins
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube
    networks:
      - autodoc  
  # getting postgres DB

  #############################################################
  ####################     DATABASES       ####################
  #############################################################

  autodoc-db-dev:
    image: postgres:11
    container_name: autodoc-db-dev
    ports:
      - 5132:5432
    environment:
      POSTGRES_USER: ocp
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: autodoc
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./db-initProd/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - autodoc

  autodoc-db-QA:
    image: postgres:11
    container_name: autodoc-db-QA
    ports:
      - 5232:5432
    environment:
      POSTGRES_USER: ocp
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: autodoc
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./db-initProd/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - autodoc       


  autodoc-db-preprod:
    image: postgres:11
    container_name: autodoc-db-preprod
    ports:
      - 5332:5432
    environment:
      POSTGRES_USER: ocp
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: autodoc
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./db-initProd/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - autodoc

  autodoc-db-production:
    image: postgres:11
    container_name: autodoc-db-production
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ocp
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: autodoc
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./db-initProd/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - autodoc


  #############################################################
  #######################    APPS       #######################
  #############################################################

  ###########################################
  ###########  webservice ###################

  autodoc-webservice:
    image: autodoc_webservice
    container_name: webservice-dev
    build: autodoc-webservice/.
    ports:
     - 8080:8080
    volumes:
      - logs:/usr/app/resources
    depends_on:
      - autodoc-db-dev
    networks:
      - autodoc

  ###########################################
  ###########  wecbapp ###################

  autodoc-webapp:
    image: autodoc_webapp
    container_name: webapp-dev
    build: autodoc-webapp/.
    ports:
        - 8085:8080
    volumes:
      - logs:/usr/app/resources    
    depends_on:
      - webservice
    networks:
      - autodoc


###########################################
###########   volumes   ###################

volumes:  
  pg-data:
  logs:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:

networks:
  autodoc:

