/*DROP DATABASE IF EXISTS autodoc;*/

/*CREATE DATABASE  autodoc;
*/

DROP TABLE IF EXISTS car;

CREATE TABLE IF NOT EXISTS car
(
    id   INTEGER      NOT NULL,
    name VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);
